# Generated by Django 5.0.6 on 2024-09-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product',
            new_name='item',
        ),
    ]
