# Generated by Django 5.0.6 on 2024-09-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_item_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='item',
        ),
    ]
