# Generated by Django 5.0.6 on 2024-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlist_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='leading_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
