# Generated by Django 5.0.6 on 2024-09-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlist_bid_count_auctionlist_leading_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='image_url',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='leading_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
