# Generated by Django 5.0.6 on 2024-09-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_image_url_alter_auctionlist_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
